model:
  input_size: 264
  hidden_size: 100
  num_layers: 1
  dropout: 0
  linear_output: 256
  act_fn: 'relu'

# model paths
beats_model_path: '/model/BEATs_iter3_plus_AS2M.pt'

# training parameters
train_data: '/data/train.json'
val_data: '/data/train.json'
model_path: '/model/haaqi_net_best.pth'
save_model_path: '/model/haaqi_net.pth'
batch_size: 1
num_workers: 4
epochs: 10